### ISSUE TITLE
evaluar y configurar web server Procfile y Puma

### ISSUE THREAD

**Issue by jgabardini** [kleer-la/eventer#83]
evaluar si usar Puma -> Si, es el default en Rails 5

- [x] crear el Procfile
       Entendiendo reporte de problemas de Heroku https://dev.to/lawrence_eagles/causes-of-heroku-h10-app-crashed-error-and-how-to-solve-them-3jnl
- [x] Resolver problema de memoria
       https://devcenter.heroku.com/changelog-items/1683

**Comment by carlospeix** [comment]
https://github.com/kleer-la/fugazzeta/commit/a26f768f881672eab3e9264f694c5d57d9ac2c8d

----------------------------------
Carlos Peix
Móvil/Whatsapp: +54 911 4406 7571

**Comment by jgabardini** [comment]
en prod
